#!/usr/bin/php
<?
/*
  Add this line to the VirtualHost-Directive in apache-config:
  # DefineExternalGroup git_repo pipe DRUPAL_ROOT/modules/git_repo/git_group
*/

// Set cwd to DRUPAL_ROOT, set variables
$p=explode("/", $_SERVER['PHP_SELF']);
chdir(implode("/", array_slice($p, 0, sizeof($p)-3)));
define('DRUPAL_ROOT', getcwd());
$_SERVER['REMOTE_ADDR']="0.0.0.0";

// Read user and id of accessed node from stdin
$stdin=fopen("php://stdin", "r");
$name=trim(fgets($stdin));
$access=trim(fgets($stdin));
fclose($stdin);

// Access is of form 'type:nid', e.g. 'view:25'
$access=explode(":", $access);
$nid=$access[1];
$access=$access[0];

// Maybe we can ask cache?
include_once "cache.php";
if(($auth=_git_repo_cache_get(md5("group|$name|$access|$nid")))!==null) {
  exit($auth);
}

//the Drupal root, relative to the directory of the path
require_once './includes/bootstrap.inc';
drupal_bootstrap(DRUPAL_BOOTSTRAP_FULL);

// Load user and node
$user=user_load_by_name($name);
$node=node_load($nid);

// check access
$auth=1; // sorry, dude :(
if(node_access($access, $node, $user)) {
  $auth=0; // access granted
}

// save auth for later use
_git_repo_cache_set(md5("group|$name|$access|$nid"), $auth);

exit($auth);
