#!/usr/bin/php
<?
/*
  Add this line to the VirtualHost-Directive in apache-config:
  # DefineExternalGroup git_repo pipe DRUPAL_ROOT/modules/git_repo/git_group
*/

// Set cwd to DRUPAL_ROOT, set variables
$p=explode("/", $_SERVER['PHP_SELF']);
chdir(implode("/", array_slice($p, 0, sizeof($p)-3)));
define('DRUPAL_ROOT', getcwd());
$_SERVER['REMOTE_ADDR']="0.0.0.0";

//the Drupal root, relative to the directory of the path
require_once './includes/bootstrap.inc';
drupal_bootstrap(DRUPAL_BOOTSTRAP_FULL);

// Read user and id of accessed node from stdin
$stdin=fopen("php://stdin", "r");
$user=trim(fgets($stdin));
$nid=trim(fgets($stdin));
fclose($stdin);

// Load user and node
$user=user_load($user);
$node=node_load($nid);

// check access
if(node_access('view', $node, $user)) {
  exit(0); // access granted
}

exit(1); // sorry, dude :(
