<?php
// $Id$

function git_repo_admin() {
  $form = array();

  $form['git_repo_base_path'] = array(
    '#type' => 'textfield',
    '#title' => t('Base Path'),
    '#default_value' => variable_get('git_repo_base_path'),
    '#description' => t('Please provide a (web server writeable) directory, where the git repositories will be created'),
    '#required' => true,
  );

  return system_settings_form($form);
}

function git_repo_menu() {
  $items = array();

  $items['admin/structure/git_repo'] = array(
    'title' => 'Git Repository',
    'description' => 'Configures the Git Repository module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('git_repo_admin'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

function _git_repo_create($id, $title) {
  // Get Base Path of Git Repos
  $git_repo_base_path=variable_get('git_repo_base_path');
  if(!$git_repo_base_path) {
    drupal_set_message("Git Repo: \$git_repo_base_path not set");
    return;
  }

  // Check validity of Base Path
  if(!is_dir($git_repo_base_path)) {
    drupal_set_message("Git Repo: Base Path '$git_repo_base_path' does not exist", "error");
    return;
  }
  if(!is_writeable($git_repo_base_path)) {
    drupal_set_message("Git Repo: Base Path '$git_repo_base_path' is not writeable", "error");
    return;
  }

  // Calculate path
  $path="$git_repo_base_path/$id";

  // Create path
  if(!mkdir($path)) {
    return;
  }

  // Change to path
  if(!chdir($path)) {
    return;
  }

  // Create repo
  system("git init --bare");
  system("git update-server-info");

  // Set Repo-Information
  $f=fopen("description", "w");
  fprintf($f, $title);
  fclose($f);

  // Create .htaccess-file
  $f=fopen("$path/.htaccess", "w");
  fprintf($f, "AuthType Basic\n");
  fprintf($f, "AuthName \"Group $id\"\n");
  fprintf($f, "AuthBasicProvider external\n");
  fprintf($f, "AuthExternal cg2\n");
  fprintf($f, "GroupExternal cg2\n");
  fprintf($f, "Require group og_$id tutor\n");
  fclose($f);

  // Say something
  $t_args=array("%id"=>$id);
  drupal_set_message(t('Git Repository %id has been created.', $t_args));
}

function git_repo_node_insert($node) {
  // Only when content type is group
  if($node->type!="group") {
    return;
  }

  // Do the work
  _git_repo_create($node->nid, $node->title);
}
